### ISSUE TITLE
Aprimorar as classes que estão incompletas

### ISSUE THREAD

**Issue by Felipe-mth** [Felipe-mth/sistemaCondominio-POO#2]
Preparar a documentação para essas classes no Draw.io para que elas sejam adicionadas ao código.
- [x] Gestão de usuário
- [x] Auditoria
- [x] Contabilidade

**Comment by guisilveira** [comment]
Adicionada documentação da classe de Gestão de Usuário e coloquei os métodos da Auditoria

**Comment by JoseVictorRego** [comment]
Atualização da classe contabilidade. feita por min e HewerP.
